name: Build Deb

on:
  push:
    paths:
      - 'release-versions/*'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup which version of Python to use
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install permasigner
      - name: Install permasigner
        run: |
          python3 -m pip install --upgrade pip
          pip3 install permasigner

      # Obtain uYouPlus URL from file
      - name: Obtain uYouPlus URL from file
        id: getURL
        run: |
          echo "::set-output name=uYouPlusURL::$(sed -n 2p release-versions/uYouPlus-version.txt)"

      # Run permasigner
      - name: Run script
        run: permasigner -u ${{ steps.getURL.outputs.uYouPlusURL }} -d -o output/

      # Commit deb to repo
      - name: Commit latest release version
        run: |
          ls -la .
          ls -la output/
          git config --global user.name 'latest-release-bot'
          git config --global user.email 'latest-release-bot@example.com'
          # git commit -am "update: New uYouPlus deb"
          # git push
