name: build-deb

on:
  push:
    paths:
      - 'release-versions/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository for job to access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up which version of Python to use
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install permasigner
      - name: Install permasigner
        run: |
          python3 -m pip install --upgrade pip
          pip3 install permasigner

      # Obtain IPA URL and version from file
      - name: Obtain IPA URL and version from file
        id: get-info
        run: |
          echo "::set-output name=uYouPlus-url::$(sed -n 2p release-versions/uYouPlus-version.txt)"
          echo "::set-output name=uYouPlus-version::$(sed -n 1p release-versions/uYouPlus-version.txt)"

      # Build DEB from IPA with permasigner
      - name: Build DEB from IPA with permasigner
        run: permasigner -u ${{ steps.get-info.outputs.uYouPlus-url }} -d -o debs/

      # Generate Packages.bz2 with scripts
      - name: Generate Packages.bz2 with scripts
        run: |
          bash scripts/UpdateRepo.sh

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name 'latest-release-bot'
          git config --global user.email 'latest-release-bot@example.com'

      # Commit DEB file(s) and updated Packages.bz2 to repository
      - name: Commit DEB file(s) and updated Packages.bz2 to repository
        run: |
          git add debs/
          git add Packages.bz2
          git commit -m "update: uYouPlus ${{ steps.get-info.outputs.uYouPlus-version }}"

      # Push commits to GitHub
      - name: Push commits to GitHub
        run: |
          git push
