name: Get latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/qnblackcat/uYouPlus/releases/latest | jq -r ".tag_name" > release-versions/uYouPlus-version.txt
          curl -sL https://api.github.com/repos/qnblackcat/uYouPlus/releases/latest | jq -r '.assets[]' | jq -r '.browser_download_url' >> release-versions/uYouPlus-version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'latest-release-bot'
          git config --global user.email 'latest-release-bot@example.com'
          git commit -am "update: New uYouPlus release"
          git push
